Repository Team-Partage/partage_web, pull requests merged in 2024-06, with the labels that each got.

#9 Feature 8/api
  package.json
  src/lib/fetcher/index.ts
  src/services/auth/index.ts
  src/services/auth/type.ts
  src/services/channel/index.ts
  src/services/channel/type.ts
  src/services/playlist/index.ts
  src/services/playlist/type.ts
  src/services/user/index.ts
  src/services/user/type.ts
  yarn.lock
Labels: 개발

#27 Feat 24/search bar
  .gitignore
  .husky/_/h
  .husky/_/husky.sh
  .husky/_/pre-commit
  public/Close.svg
  public/search-sb.svg
  src/app/globals.css
  src/app/page.tsx
  src/app/search/page.tsx
  src/components/ChannelCreatorBox.tsx
  src/components/SearchBar.tsx
  src/services/channel/index.ts
  src/stores/useChannelStore.ts
  tailwind.config.ts
  yarn.lock
Labels: 개발

#36 Design: 35/header
  README.md
  public/logo.svg
  public/plus_bk.svg
  src/app/layout.tsx
  src/components/Header.tsx
  src/utils/route.ts
  tailwind.config.ts
Labels: 디자인

#37 Docs: Readme 수정
  README.md
Labels: 문서

#42 Chore 41/image
  src/app/(main)/_components/ChannelItem.tsx
Labels: bug

#43 Feature 10/auth page
  src/app/mypage/_components/EditMyInfo.tsx
  src/auth.ts
  src/lib/fetcher/index.ts
  yarn.lock
Labels: bug

#48 Design: 메인페이지에서 채널색상에 따라 tailwind 적용을 style로 변경
  src/app/(main)/_components/ChannelItem.tsx
  src/app/(main)/_components/Hashtags.tsx
  src/utils/getChannelColorClassName.ts
  src/utils/getChannelHoverBorderColor.ts
Labels: 디자인

#49 ColorChips 리팩토링 및 TagInput 컴포넌트 추가
  src/app/mypage/_components/EditMyInfo.tsx
  src/components/ColorChips.tsx
  src/components/TagInput.tsx
  src/components/modal/CreateChannelModal.tsx
  src/utils/hexToColorName.ts
Labels: 개발
